2023-08-06 21:45:54,596 - server.logger_ser - ERROR - app.general_document_classification():82 - Id not found!
2023-08-06 21:45:54,600 - server.logger_ser - ERROR - app.general_document_classification():104 - 
Traceback (most recent call last):
  File "/home/namhai18/study/ExtractID-from-namecard/classify_image/server/app.py", line 83, in general_document_classification
    raise Exception
Exception
2023-08-06 21:50:16,495 - server.logger_ser - ERROR - app.general_document_classification():82 - Id not found!
2023-08-06 21:50:16,496 - server.logger_ser - ERROR - app.general_document_classification():104 - 
Traceback (most recent call last):
  File "/home/namhai18/study/ExtractID-from-namecard/classify_image/server/app.py", line 83, in general_document_classification
    raise Exception
Exception
2023-08-06 21:50:47,229 - server.logger_ser - ERROR - app.general_document_classification():82 - Id not found!
2023-08-06 21:50:47,230 - server.logger_ser - ERROR - app.general_document_classification():104 - 
Traceback (most recent call last):
  File "/home/namhai18/study/ExtractID-from-namecard/classify_image/server/app.py", line 83, in general_document_classification
    raise Exception
Exception
